### ISSUE TITLE
tutorial not working on windows

### ISSUE THREAD

**Issue by eurochriskelly** [dthree/vantage#3] opened 2015-06-22 19:38 UTC
Step 5: start server 3001
Successfully spawned server

Step 6: vantage 3001
Error connecting. 503 service unavailable
  ## You're in. Notice the prompt changed.

(Prompt does not change)

Step 7: port
undefined

An extrenal process is spawned but it does not repond. Any idea what's causing this?

**Comment by k0dek0mmand0** [comment] 2015-06-22 19:47
Noticed same symptoms on Debian 8.1, node v0.12.4, with vantage installed from npm repo.

**Comment by dthree** [comment] 2015-06-22 19:53
Hmm. Looks like something with pm2 having trouble spawning the app. I might just skip pm2 and directly start it up. Thanks for pointing this out.

**Comment by dthree** [comment] 2015-06-22 21:32
Hey - pm2 should throw a stderr log into the root of the vantage directory if it has trouble spawning the tutorial. I'm having trouble reproducing the problem - could either of you check if you have anything in that stderr file?

**Comment by k0dek0mmand0** [comment] 2015-06-22 21:51
I checked both my Windows and Debian machines and none of them contain any stderr files.

What's strange is that it doesn't say it couldn't connect, but rather that it gets a `503` error from the server. Could it be that somewhere in server code an exception is thrown, but it's caught by the default handler and just handled as a generic server error?

Maybe the simplest way to reproduce would be to install a fresh Debian 8.1 and `nvm` onto a virtual machine, then to run `nvm install v0.12.4` then `npm install -g vantage`

I tried v0.11.15 with same results.

**Comment by eurochriskelly** [comment] 2015-06-22 21:57
no stderr file here either in cwd (windows 7 64bit/node v0.12.4)

**Comment by k0dek0mmand0** [comment] 2015-06-22 22:12
Not sure about my previous `503` idea anymore. I do `run server 9991` for example and is *says* it's succeeded, but `netstat -a` shows no one listening on port 9991. PM2 seems to be running daemonized, though.

**Comment by dthree** [comment] 2015-06-22 22:20
Reproduced it with a Docker image.

Haha - silly me. I copied `server.js` (which is the spawned image) originally off of one of my test files that did a similar thing, and I never removed `should.js` as a dependency. Couldn't reproduce it myself as `should` was installed globally. 

Can you try v0.2.14 on your box now?

**Comment by dthree** [comment] 2015-06-22 22:23
eurochriskelly - looks like the pm2 stderr files were dumping in a different place /root/.pm2/... on my box.

**Comment by k0dek0mmand0** [comment] 2015-06-22 22:30
Cloned latest and it works. Thanks!

I found another issue though. Try:
`start server 9991`
`vantage 9991`
`vantage 9991`

**Comment by dthree** [comment] 2015-06-22 22:38
Great!
-
Hahaha - yeah, that's bound to cause problems. I'll have to add a check to ensure you aren't talking to yourself.

**Comment by dthree** [comment] 2015-06-22 22:42
Closing this issue - want to keep one issue per... issue. You can open up another one for that problem you just mentioned.

**Closed by dthree** 2015-06-22 22:42 UTC

**Comment by eurochriskelly** [comment] 2015-06-22 22:45
Thanks! Will try latest tomorrow.

On Tue, Jun 23, 2015 at 12:42 AM, dc <notifications@github.com> wrote:

> Closing this issue - want to keep one issue per... issue. You can open up
> another one for that problem you just mentioned.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dthree/vantage/issues/3#issuecomment-114290715>.
>



-- 
Chris

**Comment by eurochriskelly** [comment] 2015-06-23 09:14
Tried again on windows 7 64-bit but no luck.
Cloned vantage 0.2.14. npm install. Repeated steps. It says successfully
spawned server but I do not see the cmd window flash like previously. pm2
list reports no processes. When I try to connect I still get Error
connecting: 503 services unavailable.

On Tue, Jun 23, 2015 at 12:45 AM, Chris Kelly <eurochriskelly@gmail.com>
wrote:

> Thanks! Will try latest tomorrow.
>
> On Tue, Jun 23, 2015 at 12:42 AM, dc <notifications@github.com> wrote:
>
>> Closing this issue - want to keep one issue per... issue. You can open up
>> another one for that problem you just mentioned.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/dthree/vantage/issues/3#issuecomment-114290715>.
>>
>
>
>
> --
> Chris
>



-- 
Chris

**Comment by k0dek0mmand0** [comment] 2015-06-23 09:27
I can confirm Windows behaviour. I finally found pm2 logs in `c:\Users\[MyUsername]\.pm2\logs`.
Anyway, the error log contains:

```
Error: Implement me. Unknown stdin file type!
    at process.stdin (node.js:558:17)
    at Object.Interface.createInterface (c:\Users\[REDACTED]\Desktop\vantage\node_modules\inquirer\node_modules\readline2\index.js:30:43)
    at PromptUI.UI (c:\Users\[REDACTED]\Desktop\vantage\node_modules\inquirer\lib\ui\baseUI.js:23:40)
    at new PromptUI (c:\Users\[REDACTED]\Desktop\vantage\node_modules\inquirer\lib\ui\prompt.js:26:8)
    at Object.promptModule [as prompt] (c:\Users\[REDACTED]\Desktop\vantage\node_modules\inquirer\lib\inquirer.js:27:14)
    at Vantage.vantage._prompt (c:\Users\[REDACTED]\Desktop\vantage\lib\vantage.js:707:21)
    at Vantage.vantage.show (c:\Users\[REDACTED]\Desktop\vantage\lib\vantage.js:589:8)
    at create (c:\Users\[REDACTED]\Desktop\vantage\examples\tutorial\server.js:78:6)
    at Object.<anonymous> (c:\Users\[REDACTED]\Desktop\vantage\examples\tutorial\server.js:84:11)
    at Module._compile (module.js:460:26) 
```
Is it possible that this is an issue with `inquirer`?

**Comment by eurochriskelly** [comment] 2015-06-23 12:30
I'm seeing the same thing in error log.

On Tue, Jun 23, 2015 at 11:27 AM, k0dek0mmand0 <notifications@github.com>
wrote:

> I can confirm Windows behaviour. I finally found pm2 logs in
> c:\Users\[MyUsername]\.pm2\logs.
> Anyway, the error log contains:
>
> Error: Implement me. Unknown stdin file type!
>     at process.stdin (node.js:558:17)
>     at Object.Interface.createInterface (c:\Users\[REDACTED]\Desktop\vantage\node_modules\inquirer\node_modules\readline2\index.js:30:43)
>     at PromptUI.UI (c:\Users\[REDACTED]\Desktop\vantage\node_modules\inquirer\lib\ui\baseUI.js:23:40)
>     at new PromptUI (c:\Users\[REDACTED]\Desktop\vantage\node_modules\inquirer\lib\ui\prompt.js:26:8)
>     at Object.promptModule [as prompt] (c:\Users\[REDACTED]\Desktop\vantage\node_modules\inquirer\lib\inquirer.js:27:14)
>     at Vantage.vantage._prompt (c:\Users\[REDACTED]\Desktop\vantage\lib\vantage.js:707:21)
>     at Vantage.vantage.show (c:\Users\[REDACTED]\Desktop\vantage\lib\vantage.js:589:8)
>     at create (c:\Users\[REDACTED]\Desktop\vantage\examples\tutorial\server.js:78:6)
>     at Object.<anonymous> (c:\Users\[REDACTED]\Desktop\vantage\examples\tutorial\server.js:84:11)
>     at Module._compile (module.js:460:26)
>
> Is it possible that this is an issue with inquirer?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dthree/vantage/issues/3#issuecomment-114419169>.
>



-- 
Chris
