### ISSUE TITLE
Repeated output

### ISSUE THREAD

**Issue by wonderdogone** [dthree/vantage#40] opened 2015-09-03 19:02 UTC
when you run the simple example like
var vantage = require("vantage")();

// Add the command "foo", which logs "bar".
vantage
  .command("foo")
  .description("Outputs 'bar'.")
  .action(function(args, callback) {
   this.log("bar");
    callback();
  });

vantage
  .delimiter("websvr~$")
  .listen(5003)
  .show();

and you type foo, you get foo repeated then bar. Why is foo repeating?
websvr~$ foo
websvr~$ foo (this is the repeated output)
bar

**Comment by dthree** [comment] 2015-09-03 19:39
Can you try this for me:

After starting the app, press [enter] a few times, and then do the `foo` command. Does it still repeat this?

I had noticed a bug that the first output is doubled, earlier. Maybe this is the same thing.

**Comment by wonderdogone** [comment] 2015-09-03 19:48
yup same result after many returns
websvr~$ 
websvr~$ 
websvr~$ 
websvr~$ 
websvr~$ 
websvr~$ 
websvr~$ 
websvr~$ 
websvr~$ 
websvr~$ 
websvr~$ 
websvr~$ 
websvr~$ 
websvr~$ 
websvr~$ 
websvr~$ 
websvr~$ 
websvr~$ foo
websvr~$ foo
websvr~$

**Comment by dthree** [comment] 2015-09-03 19:56
K looking into it.

**Comment by wonderdogone** [comment] 2015-09-04 21:15
it has something to do with the input. after a few commands I start getting breaking on each character as i type

dive~$ s
dive~$ sh
dive~$ sho
dive~$ show
dive~$ shows
dive~$ 
dive~$ 
dive~$ 
dive~$ 
dive~$

**Comment by dthree** [comment] 2015-09-04 22:37
Hmm. If your vantage code is small, could you please paste it here? Also, what terminal are you using?
Thanks.

**Comment by G3E9** [comment] 2015-09-09 03:24
* The `server.js` code copied from the readme 
* Node.js `v4.0.0`
* Vantage `1.5.1`
* PuTTY `Release 0.63`

Using the above, I too am experiencing the same as @wonderdogone. What I've found is the vertical height of the terminal determines this behavior, see below.
### Too tall of terminal
![tootall](https://cloud.githubusercontent.com/assets/13586713/9752559/8a39a0c8-5677-11e5-8fc8-3907d7c7bf32.png)
### Terminal just tall enough
![tallenough](https://cloud.githubusercontent.com/assets/13586713/9752567/af1529da-5677-11e5-9e9d-dd2c9c7176c0.png)
Once I have reached the bottom of my terminal, my keystrokes are no longer repeated (e.g. shown in the second photo, `f` and `o` was not repeated when I was typing `foo` at the bottom of the terminal.)

**Comment by dthree** [comment] 2015-09-09 16:25
@G3E9 you nailed it. That's so weird. It's not so much the terminal height, as the cursor has to be on the bottom of the page.

Going to look into this soon.

**Comment by G3E9** [comment] 2015-09-09 16:26
![heldkey](https://cloud.githubusercontent.com/assets/13586713/9767763/684a8b76-56e5-11e5-811a-60858b44ce91.png)
A better example.

**Comment by dthree** [comment] 2015-09-09 16:27
Yeah - I was able to reproduce it. Thanks.

Vorpal just recently switched to a newer version of inquirer (10x smaller), and this broke a bunch of things. This looks like the last thing left.

**Comment by G3E9** [comment] 2015-09-09 16:31
>  It's not so much the terminal height, as the cursor has to be on the bottom of the page.
Right on. While I was just about to test with Vorpal, you sound like your on top of it!.. I've really been enjoying Vantage in my projects, awesome work!

**Comment by dthree** [comment] 2015-09-09 17:08
Thanks! Really glad you find it helpful!

**Comment by wonderdogone** [comment] 2015-09-11 09:11
yea I figured out its happening most of the time in the morning when i open a new terminal and cursor is at the top.

**Comment by dthree** [comment] 2015-10-11 20:40
This is fixed in Vorpal - I just have to migrate Vantage to the latest version of Vorpal.

**Comment by fiznool** [comment] 2016-04-09 19:41
@dthree 

> I had noticed a bug that the first output is doubled, earlier. Maybe this is the same thing.

I'm seeing this issue, is there any fix?

**Comment by xori** [comment] 2016-04-11 18:12
I only see it when I connect from another process and I found that just typing `vantage` to open the initial console, then `vantage server:port` to connect to the intended server, stops the double output.
```sh
PS C:\code\bin\shar> vantage
local@mycomputer~$ vantage myserver:port
my-vantage-prompt> 
```

**Comment by samhagman** [comment] 2016-05-16 19:50
Any update @dthree on integrating the newest Vorpal to resolve this issue as well as issues like #56 and anyone else that will try to use newer vorpal APIs?   Thanks for this really cool library by the way.

**Comment by zakhenry** [comment] 2016-07-20 22:12
@samhagman the version of vorpal that vantage uses was brought up to date in #62 , by any chance was this issue fixed? I haven't noticed the issue in my own work. cc @dthree

**Comment by dthree** [comment] 2016-07-22 03:37
@zakhenry I believe this was fixed.

**Closed** 2016-07-22 03:37 UTC
